openapi: 3.0.0
info:
  title: "SAMI Bot Tools"
  description: "Dedicated API for the Dify.ai agent. Includes Contract management, Payment links, Maintenance requests, and Vehicle registration."
  version: "2.2.0"

servers:
  - url: <ngrok_url>

components:
  securitySchemes:
    BotAuth:
      type: apiKey
      in: header
      name: x-bot-api-key
      
  schemas:
    # --- Enums ---
    MaintenanceCategoryEnum:
      type: string
      enum: [plumbing, electrical, hvac, appliance, structural, cleaning, other]
    MaintenancePriorityEnum:
      type: string
      enum: [low, normal, high, urgent]
    VehicleTypeEnum:
      type: string
      enum: [car, motorcycle, truck, van, other]

    # --- Response Schemas (for Context) ---
    UnpaidBill:
      type: object
      properties:
        bill_id: { type: integer }
        bill_number: { type: string }
        description: { type: string }
        total_due: { type: number }
        due_date: { type: string, format: "date-time" }
    
    ActiveContract:
      type: object
      description: "Details about the tenant's current contract."
      properties:
        contract_id: { type: integer }
        start_date: { type: string, format: "date-time" }
        end_date: { type: string, format: "date-time" }
        current_end_date: { type: string, format: "date-time", description: "The actual end date considering addendums." }
        rent_amount: { type: number }
        deposit_amount: { type: number }
        status: { type: string, enum: [active, pending, expired] }
        has_file: { type: boolean, description: "If true, the bot should offer to download the contract." }
        addendum_note: { type: string, description: "Summary of changes from the latest addendum." }

    Contact:
      type: object
      properties:
        role: { type: string, enum: [Manager, Owner] }
        name: { type: string }
        phone: { type: string }
    PendingMaintenance:
      type: object
      properties:
        request_id: { type: integer }
        title: { type: string }
        status: { type: string }
        created_at: { type: string, format: "date-time" }
    PendingRegistration:
      type: object
      properties:
        registration_id: { type: integer }
        status: { type: string }
        type: { type: string }
        license_plate: { type: string }
    ActiveVehicle:
      type: object
      properties:
        vehicle_id: { type: integer }
        type: { type: string }
        license_plate: { type: string }
        brand: { type: string }
    RegulationTitle:
      type: object
      properties:
        regulation_id: { type: integer }
        title: { type: string }
        status: { type: string }
        target: { type: string, enum: [all, tenants, management] }
        effective_date: { type: string, format: "date-time" }
    CreateFeedback:
      type: object
      properties:
        comment:
          type: string
          description: "Nội dung feedback của người dùng."
      required:
        - comment

security:
  - BotAuth: []

# --- API Endpoints ---
paths:

  # --- TOOL 1: CONTEXT ---
  /api/bot/context:
    get:
      summary: "Get Tenant Context (Bot API)"
      description: "CRITICAL: Call this tool FIRST. Gets all data about the tenant specified by `tenant_user_id`."
      operationId: "getTenantContext"
      tags:
        - Tenant Info
      parameters:
        - name: tenant_user_id
          in: query
          required: true
          description: "The ID of the tenant chatting with the bot."
          schema:
            type: integer
      responses:
        '200':
          description: "Successful retrieval."
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    type: object
                    properties:
                      tenant_user_id: { type: integer }
                      tenant_name: { type: string }
                      room_id: { type: integer }
                      room_number: { type: string }
                      current_date: { type: string, format: "date-time" }
                      unpaid_bills: { type: array, items: { $ref: '#/components/schemas/UnpaidBill' } }
                      active_contract: { $ref: '#/components/schemas/ActiveContract' }
                      contacts: { type: array, items: { $ref: '#/components/schemas/Contact' } }
                      pending_maintenance: { type: array, items: { $ref: '#/components/schemas/PendingMaintenance' } }
                      pending_registrations: { type: array, items: { $ref: '#/components/schemas/PendingRegistration' } }
                      active_vehicles: { type: array, items: { $ref: '#/components/schemas/ActiveVehicle' } }
        '401':
          description: "Unauthorized. The key is missing or invalid."

  # --- TOOL 2: CREATE MAINTENANCE ---
  /api/bot/maintenance/create:
    post:
      summary: "Create Maintenance Request"
      operationId: "createMaintenanceRequest"
      tags: [Maintenance]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, title]
              properties:
                tenant_user_id: { type: integer }
                title: { type: string }
                description: { type: string }
                category: { $ref: '#/components/schemas/MaintenanceCategoryEnum' }
                priority: { $ref: '#/components/schemas/MaintenancePriorityEnum' }
                room_id: { type: integer }
      responses:
        '201': { description: "Created" }
        '401': { description: "Unauthorized." }

  # --- TOOL 3 & 4: UPDATE/DELETE MAINTENANCE ---
  /api/bot/maintenance/{id}:
    put:
      summary: "Update Maintenance Request"
      operationId: "updateMaintenanceRequest"
      tags: [Maintenance]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
                title: { type: string }
                description: { type: string }
                category: { $ref: '#/components/schemas/MaintenanceCategoryEnum' }
                priority: { $ref: '#/components/schemas/MaintenancePriorityEnum' }
      responses:
        '200': { description: "Updated successfully." }
          
    delete:
      summary: "Delete Maintenance Request"
      operationId: "deleteMaintenanceRequest"
      tags: [Maintenance]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
      responses:
        '200': { description: "Deleted successfully." }

  # --- TOOL 5: CREATE VEHICLE REGISTRATION ---
  /api/bot/vehicle-registration/create:
    post:
      summary: "Register New Vehicle"
      operationId: "createVehicleRegistration"
      tags: [Vehicle]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, type, license_plate]
              properties:
                tenant_user_id: { type: integer }
                type: { $ref: '#/components/schemas/VehicleTypeEnum' }
                license_plate: { type: string }
                brand: { type: string }
                color: { type: string }
                note: { type: string }
      responses:
        '201': { description: "Registration request created." }

  # --- TOOL 6: UPDATE VEHICLE REGISTRATION ---
  /api/bot/vehicle-registration/{id}:
    put:
      summary: "Update Vehicle Registration"
      description: "Updates a pending vehicle registration. Only works if status is 'requested'."
      operationId: "updateVehicleRegistration"
      tags: [Vehicle]
      parameters:
        - name: id
          in: path
          required: true
          description: "The registration assignment_id to update."
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - tenant_user_id
              properties:
                tenant_user_id:
                  type: integer
                  description: "The ID of the tenant attempting to update the request."
                type:
                  $ref: '#/components/schemas/VehicleTypeEnum'
                license_plate:
                  type: string
                brand:
                  type: string
                color:
                  type: string
                note:
                  type: string
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
      responses:
        '200':
          description: "Updated successfully."
        '400':
          description: "Validation error or invalid state."
        '403':
          description: "Forbidden (e.g., registration not owned by tenant)."

  # --- TOOL 8: CANCEL VEHICLE REGISTRATION ---
  /api/bot/vehicle-registration/{id}/cancel:
    post:
      summary: "Cancel Vehicle Registration"
      description: "Cancels a pending ('requested') vehicle registration."
      operationId: "cancelVehicleRegistration"
      tags: [Vehicle]
      parameters:
        - name: id
          in: path
          required: true
          description: "The registration assignment_id to cancel."
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant_user_id
              properties:
                tenant_user_id:
                  type: integer
                  description: "The ID of the tenant cancelling the request."
                cancellation_reason:
                  type: string
                  description: "Reason for cancellation (optional)."
      responses:
        '200':
          description: "Cancelled successfully."
        '400':
          description: "Validation error or invalid state."
        '403':
          description: "Forbidden."

  # --- REGULATIONS Tools ---
  /api/bot/regulations:
    get:
      summary: "Get Regulations List"
      operationId: "getAllRegulations"
      tags: [Regulations]
      responses:
        '200': { description: "Success" }
        '401': { description: "Unauthorized" }

  /api/bot/regulation/{id}/feedback:
    post:
      summary: "Add Regulation Feedback"
      operationId: "addRegulationFeedback"
      tags: [Regulations]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, comment]
              properties:
                tenant_user_id: { type: integer }
                comment: { type: string }
      responses:
        '201':
          description: "Feedback added successfully."
        '400':
          description: "Invalid input."
        '401':
          description: "Unauthorized."

  # --- PAYMENT LINK ---
  /api/bot/create-payment:
    post:
      summary: "Create Payment Link"
      description: "Generates a PayOS payment URL for a specific bill ID."
      operationId: "createPaymentLink"
      tags: [Payment]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, bill_id]
              properties:
                tenant_user_id:
                  type: integer
                bill_id:
                  type: integer
      responses:
        '200':
          description: "Link created."
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      checkoutUrl: { type: string }

  # --- DOWNLOAD CONTRACT ---
  /api/bot/contract/download:
    post:
      summary: "Get Contract Download Link"
      description: "Generates a temporary S3 link for the tenant's active contract PDF."
      operationId: "getMyContractFile"
      tags: [Contract]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
      responses:
        '200':
          description: "Returns the download URL."
          content:
            application/json:
              schema:
                type: object
                properties:
                  url: { type: string }
                  message: { type: string }
