#
# OpenAPI 3.0 Specification for SAMI Tenant Agent
#
openapi: 3.0.0
info:
  title: "SAMI Bot Tools"
  description: "API for the Smart Apartment Management Interface, providing tools for the Dify.ai tenant agent. All endpoints require tenant authentication."
  version: "1.1.0"

servers:
  - url: <ngrok_url>/api

components:
  securitySchemes:
    TenantAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Tenant's JWT access token obtained after login."
      
  schemas:
    # --- Enums ---
    MaintenanceCategoryEnum:
      type: string
      enum: [plumbing, electrical, hvac, carpentry, cleaning, other]
    MaintenancePriorityEnum:
      type: string
      enum: [low, normal, high, urgent]
    VehicleTypeEnum:
      type: string
      enum: [car, motorcycle, truck, van, other]

    # --- Response Schemas (for Context) ---
    UnpaidBill:
      type: object
      properties:
        bill_id: { type: integer }
        bill_number: { type: string }
        description: { type: string }
        total_due: { type: number }
        due_date: { type: string, format: "date-time" }
    ActiveContract:
      type: object
      properties:
        contract_id: { type: integer }
        start_date: { type: string, format: "date-time" }
        end_date: { type: string, format: "date-time" }
        rent_amount: { type: number }
    Contact:
      type: object
      properties:
        role: { type: string, enum: [Manager, Owner] }
        name: { type: string }
        phone: { type: string }
    PendingMaintenance:
      type: object
      properties:
        request_id: { type: integer }
        title: { type: string }
        status: { type: string }
        created_at: { type: string, format: "date-time" }
    PendingRegistration:
      type: object
      properties:
        registration_id: { type: integer }
        status: { type: string }
        type: { type: string }
        license_plate: { type: string }
    ActiveVehicle:
      type: object
      properties:
        vehicle_id: { type: integer }
        type: { type: string }
        license_plate: { type: string }
        brand: { type: string }
    RegulationTitle:
      type: object
      properties:
        regulation_id: { type: integer }
        title: { type: string }
        status: { type: string }
        target: { type: string, enum: [all, tenants, management] }
        effective_date: { type: string, format: "date-time" }
    CreateFeedback:
      type: object
      properties:
        comment:
          type: string
          description: "Nội dung feedback của người dùng."
      required:
        - comment

security:
  - TenantAuth: []

# --- 4. Define the API Endpoints (The "Tools") ---
paths:

  # --- TOOL 1: THE ONLY READ TOOL ---
  /tenants/ai-context:
    get:
      summary: "Get All Tenant Context (Call this FIRST)"
      description: "CRITICAL: Call this tool FIRST in any conversation. It gets all data about the logged-in tenant (name, room ID, unpaid bills, contract, contacts, maintenance, and vehicle info)."
      operationId: "getTenantContext"
      tags:
        - Tenant Info
      responses:
        '200':
          description: "Successful retrieval of all tenant context data."
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    type: object
                    properties:
                      tenant_user_id: { type: integer }
                      tenant_name: { type: string }
                      room_id: { type: integer }
                      room_number: { type: string }
                      current_date: { type: string, format: "date-time" }
                      unpaid_bills: { type: array, items: { $ref: '#/components/schemas/UnpaidBill' } }
                      active_contract: { $ref: '#/components/schemas/ActiveContract' }
                      contacts: { type: array, items: { $ref: '#/components/schemas/Contact' } }
                      pending_maintenance: { type: array, items: { $ref: '#/components/schemas/PendingMaintenance' } }
                      pending_registrations: { type: array, items: { $ref: '#/components/schemas/PendingRegistration' } }
                      active_vehicles: { type: array, items: { $ref: '#/components/schemas/ActiveVehicle' } }
        '401':
          description: "Unauthorized. The TenantAuth token is missing or invalid."

  # --- TOOL 2: CREATE MAINTENANCE ---
  /maintenance:
    post:
      summary: "Create Maintenance Request"
      description: "Creates a new maintenance request for the logged-in tenant. The tenant's room_id (from getTenantContext) will be used by the API."
      operationId: "createMaintenanceRequest"
      tags:
        - Maintenance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: "Mô tả ngắn gọn sự cố (e.g., Vòi nước bếp bị rò rỉ)"
                description:
                  type: string
                  description: "Mô tả chi tiết hơn về sự cố."
                category:
                  $ref: '#/components/schemas/MaintenanceCategoryEnum'
                priority:
                  $ref: '#/components/schemas/MaintenancePriorityEnum'
                room_id:
                  type: integer
                  description: "ID của phòng (Lấy từ `getTenantContext`)"
              required:
                - title
                - room_id
      responses:
        '201': { description: "Request created successfully." }
        '401': { description: "Unauthorized." }

  # --- TOOL 3: UPDATE MAINTENANCE ---
  /maintenance/{id}:
    put:
      summary: "Update My Maintenance Request"
      description: "Allows a tenant to update their *own* PENDING request (e.g., change the description or priority). Cannot update status."
      operationId: "updateMyMaintenanceRequest"
      tags:
        - Maintenance
      parameters:
        - name: id
          in: path
          required: true
          description: "The request_id of the maintenance request to update (Get from `pending_maintenance` in context)."
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                description: { type: string }
                category: { $ref: '#/components/schemas/MaintenanceCategoryEnum' }
                priority: { $ref: '#/components/schemas/MaintenancePriorityEnum' }
      responses:
        '200': { description: "Updated successfully." }
          
  # --- TOOL 4: DELETE MAINTENANCE ---
    delete:
      summary: "Delete My Maintenance Request"
      description: "Allows a tenant to delete their *own* PENDING request."
      operationId: "deleteMyMaintenanceRequest"
      tags:
        - Maintenance
      parameters:
        - name: id
          in: path
          required: true
          description: "The request_id of the maintenance request to delete (Get from `pending_maintenance` in context)."
          schema:
            type: integer
      responses:
        '200': { description: "Deleted successfully." }

  # --- TOOL 5: CREATE VEHICLE REGISTRATION ---
  /vehicle/registrations:
    post:
      summary: "Create a New Vehicle Registration Request"
      description: "Submits a new request to register a vehicle. Status will be 'requested'."
      operationId: "createVehicleRegistration"
      tags:
        - Vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type: { $ref: '#/components/schemas/VehicleTypeEnum' }
                license_plate: { type: string }
                brand: { type: string }
                color: { type: string }
                note: { type: string }
              required:
                - type
                - license_plate
      responses:
        '201': { description: "Registration request created." }

  # --- TOOL 6: UPDATE VEHICLE REGISTRATION ---
  /vehicle/registrations/{id}:
    put:
      summary: "Update My Pending Registration"
      description: "Updates details for a registration that is still in 'requested' status."
      operationId: "updateVehicleRegistration"
      tags:
        - Vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: "The registration_id of the request to update (Get from `pending_registrations` in context)."
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type: { $ref: '#/components/schemas/VehicleTypeEnum' }
                license_plate: { type: string }
                brand: { type: string }
                color: { type: string }
                note: { type: string }
      responses:
        '200': { description: "Updated successfully." }

  # --- TOOL 7: DELETE VEHICLE REGISTRATION ---
    delete:
      summary: "Delete My Registration Request"
      description: "Deletes a registration that is in 'requested' or 'rejected' status."
      operationId: "deleteVehicleRegistration"
      tags:
        - Vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: "The registration_id of the request to delete (Get from `pending_registrations` in context)."
          schema:
            type: integer
      responses:
        '200': { description: "Deleted successfully." }

  # --- TOOL 8: CANCEL VEHICLE REGISTRATION ---
  /vehicle/registrations/{id}/cancel:
    post:
      summary: "Cancel My Registration"
      description: "Allows a tenant to cancel their own 'requested' registration."
      operationId: "cancelVehicleRegistration"
      tags:
        - Vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: "The registration_id of the request to cancel (Get from `pending_registrations` in context)."
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason: { type: string, description: "Lý do huỷ (optional)" }
      responses:
        '200': { description: "Cancelled successfully." }

  # --- REGULATIONS Tools ---
  /regulation:
    get:
      summary: "Get List of Regulation Titles"
      description: "Gets a list of all regulations. The agent should filter this list in its mind to show tenants only 'published' regulations where 'target' is 'all' or 'tenants'."
      operationId: "getAllRegulations"
      tags:
        - Regulations
      responses:
        '200':
          description: "A list of regulation titles and details."
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RegulationTitle'
        '401': { description: "Unauthorized" }

  /regulation/{id}/feedbacks:
    post:
      summary: "Add Feedback to a Regulation"
      description: "Allows a tenant to add a comment/feedback to a specific regulation."
      operationId: "addRegulationFeedback"
      tags:
        - Regulations
      parameters:
        - name: id
          in: path
          required: true
          description: "The regulation_id to add feedback to."
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFeedback'
      responses:
        '201':
          description: "Feedback added successfully."
        '400':
          description: "Invalid input."
        '401':
          description: "Unauthorized."
