#
# OpenAPI 3.0 Specification for SAMI Tenant Agent
#
openapi: 3.0.0
info:
  title: "SAMI Bot Tools"
  description: "API for the Smart Apartment Management Interface, providing tools for the Dify.ai tenant agent. All endpoints require tenant authentication."
  version: "1.0.0"

# 1. Set your public ngrok URL here
servers:
  - url: <ngrok_url>

# 2. Define the Security (JWT Bearer Token)
components:
  securitySchemes:
    TenantAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Tenant's JWT access token obtained after login."
      
  schemas:
    # Define enums for re-use
    MaintenanceCategoryEnum:
      type: string
      enum: [plumbing, electrical, hvac, carpentry, cleaning, other]
    
    MaintenancePriorityEnum:
      type: string
      enum: [low, normal, high, urgent]
      
    # Define a Maintenance Request Object (for responses)
    MaintenanceRequest:
      type: object
      properties:
        request_id:
          type: integer
        tenant_name:
          type: string
        room_number:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          $ref: '#/components/schemas/MaintenanceCategoryEnum'
        priority:
          $ref: '#/components/schemas/MaintenancePriorityEnum'
        status:
          type: string
        created_at:
          type: string
          format: date-time

    VehicleTypeEnum:
      type: string
      enum: [car, motorcycle, truck, van, other]

    RegistrationStatusEnum:
      type: string
      enum: [requested, approved, rejected, cancelled, expired]

    VehicleStatusEnum:
      type: string
      enum: [active, inactive, requested, deactivated]

    # Define a Vehicle Request Object (for responses)
    VehicleResponse:
      type: object
      properties:
        vehicle_id: { type: integer }
        tenant_user_id: { type: integer }
        type: { $ref: '#/components/schemas/VehicleTypeEnum' }
        license_plate: { type: string }
        brand: { type: string }
        color: { type: string }
        status: { $ref: '#/components/schemas/VehicleStatusEnum' }

    VehicleStatsResponse:
       type: object
       properties:
         total: { type: integer }
         requested: { type: integer }
         approved: { type: integer }
         rejected: { type: integer }
         byType:
           type: array
           items:
             type: object
             properties:
               type: { $ref: '#/components/schemas/VehicleTypeEnum' }
               count: { type: integer }

# 3. Apply Security Globally (All tools require the tenant's token)
security:
  - TenantAuth: []

# 4. Define the API Endpoints (The "Tools")
paths:

  # --- TOOL 1: THE MOST IMPORTANT READ TOOL ---
  /api/tenant/ai-context:
    get:
      summary: "Get All Tenant Context (Call this FIRST)"
      description: "CRITICAL: Call this tool FIRST in any conversation. It gets all data about the logged-in tenant (name, room ID, unpaid bills, contract details, and contacts)."
      operationId: "getTenantContext"
      tags:
        - Tenant Info
      responses:
        '200':
          description: "Successful retrieval of all tenant context data."
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data: { type: object } # Dify will parse the full JSON response
        '401':
          description: "Unauthorized. The TenantAuth token is missing or invalid."

  # --- TOOL 2: LIST MAINTENANCE ---
  /api/maintenance:
    get:
      summary: "Get My Maintenance Requests"
      description: "Gets a list of all maintenance requests *created by the logged-in tenant*."
      operationId: "getMyMaintenanceRequests"
      tags:
        - Maintenance
      responses:
        '200':
          description: "A list of the tenant's maintenance requests."
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MaintenanceRequest'
        '401':
          description: "Unauthorized."

  # --- TOOL 3: CREATE MAINTENANCE ---
    post:
      summary: "Create Maintenance Request"
      description: "Creates a new maintenance request for the logged-in tenant. The tenant's room_id (from getTenantContext) will be used by the API."
      operationId: "createMaintenanceRequest"
      tags:
        - Maintenance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: "Mô tả ngắn gọn sự cố (e.g., Vòi nước bếp bị rò rỉ)"
                description:
                  type: string
                  description: "Mô tả chi tiết hơn về sự cố."
                category:
                  $ref: '#/components/schemas/MaintenanceCategoryEnum'
                priority:
                  $ref: '#/components/schemas/MaintenancePriorityEnum'
                room_id:
                  type: integer
                  description: "ID của phòng (Lấy từ `getTenantContext`)"
              required:
                - title
                - room_id
      responses:
        '201':
          description: "Request created successfully."
        '400':
          description: "Invalid input."
        '401':
          description: "Unauthorized."

  # --- TOOL 4: UPDATE MAINTENANCE ---
  /api/maintenance/{id}:
    put:
      summary: "Update My Maintenance Request"
      description: "Allows a tenant to update their *own* PENDING request (e.g., change the description or priority). Cannot update status."
      operationId: "updateMyMaintenanceRequest"
      tags:
        - Maintenance
      parameters:
        - name: id
          in: path
          required: true
          description: "The request_id of the maintenance request to update."
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                category:
                  $ref: '#/components/schemas/MaintenanceCategoryEnum'
                priority:
                  $ref: '#/components/schemas/MaintenancePriorityEnum'
      responses:
        '200':
          description: "Updated successfully."
        '403':
          description: "Forbidden (e.g., trying to update a non-pending request)."
        '404':
          description: "Not found."
          
  # --- TOOL 5: DELETE MAINTENANCE ---
    delete:
      summary: "Delete My Maintenance Request"
      description: "Allows a tenant to delete their *own* PENDING request."
      operationId: "deleteMyMaintenanceRequest"
      tags:
        - Maintenance
      parameters:
        - name: delete_id
          in: path
          required: true
          description: "The request_id of the maintenance request to delete."
          schema:
            type: integer
      responses:
        '200':
          description: "Deleted successfully."
        '403':
          description: "Forbidden (e.g., trying to delete a non-pending or non-existent request)."
        '404':
          description: "Not found."

# VEHICLE MANAGEMENT
  /api/vehicle:
    get:
      summary: "Get My Registered Vehicles"
      description: "Gets a list of all vehicles (pending, approved, or rejected) registered by the logged-in tenant."
      operationId: "getMyVehicles"
      tags:
        - Vehicle
      parameters:
        - name: status
          in: query
          description: "Filter by status (e.g., requested, approved)"
          required: false
          schema:
            $ref: '#/components/schemas/RegistrationStatusEnum' # Use the enum
        - name: type
          in: query
          description: "Filter by vehicle type (e.g., car, motorcycle)"
          required: false
          schema:
            $ref: '#/components/schemas/VehicleTypeEnum' # Use the enum
      responses:
        '200':
          description: "A list of the tenant's vehicles."
          content:
            application/json:
              schema:
                type: object
                properties:
                  vehicles:
                    type: array
                    items:
                      $ref: '#/components/schemas/VehicleResponse'
                  pagination: { type: object }
        '401': { description: "Unauthorized" }

    post:
      summary: "Register a New Vehicle"
      description: "Registers a new vehicle for the tenant. The status will be 'requested'."
      operationId: "registerNewVehicle"
      tags:
        - Vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/VehicleTypeEnum'
                license_plate:
                  type: string
                  description: "Biển số xe (e.g., 29H1-12345)"
                brand:
                  type: string
                  description: "Hãng xe (e.g., Honda, Toyota)"
                color:
                  type: string
                  description: "Màu xe (e.g., Đen, Trắng)"
                note:
                  type: string
                  description: "Ghi chú thêm (e.g., Xe Lead)"
              required:
                - type
                - license_plate
      responses:
        '201':
          description: "Vehicle registered successfully."
        '400':
          description: "Invalid data (e.g., license plate already exists)."
        '401': { description: "Unauthorized" }

  /api/vehicle/{id}:
    get:
      summary: "Get My Vehicle By ID"
      description: "Gets the details of a single vehicle, if the tenant owns it."
      operationId: "getMyVehicleById"
      tags:
        - Vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: "The vehicle_id of the vehicle to view."
          schema:
            type: integer
      responses:
        '200':
          description: "Vehicle details retrieved."
        '401': { description: "Unauthorized" }
        '404': { description: "Vehicle not found." }

    put:
      summary: "Update My Pending Vehicle"
      description: "Updates details (brand, color, etc.) for a vehicle that is still in 'requested' status."
      operationId: "updateMyVehicle"
      tags:
        - Vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: "The vehicle_id of the vehicle to update."
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/VehicleTypeEnum'
                license_plate:
                  type: string
                brand:
                  type: string
                color:
                  type: string
                note:
                  type: string
      responses:
        '200':
          description: "Updated successfully."
        '403':
          description: "Forbidden (e.g., trying to update an 'approved' vehicle)."
        '401': { description: "Unauthorized" }
        '404': { description: "Vehicle not found." }

    delete:
      summary: "Delete My Vehicle Registration"
      description: "Deletes a vehicle registration that is in 'requested' or 'rejected' status. Fails if the vehicle is 'approved'."
      operationId: "deleteMyVehicle"
      tags:
        - Vehicle
      parameters:
        - name: id
          in: path
          required: true
          description: "The vehicle_id of the vehicle to delete."
          schema:
            type: integer
      responses:
        '200':
          description: "Deleted successfully."
        '403':
          description: "Forbidden (e.g., status is 'approved')."
        '401': { description: "Unauthorized" }
        '404': { description: "Vehicle not found." }

  /api/vehicle/stats:
    get:
      summary: "Get My Vehicle Statistics"
      description: "Gets a quick count of the tenant's vehicles (total, approved, pending, etc.)."
      operationId: "getMyVehicleStats"
      tags:
        - Vehicle
      responses:
        '200':
          description: "Statistics retrieved successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleStatsResponse'
        '401': { description: "Unauthorized" }
