openapi: 3.0.0
info:
  title: "SAMI Bot Tools"
  description: "Dedicated API for the Dify.ai agent. Updated for Vehicle properties and robust Payment handling."
  version: "3.1.0"

servers:
  - url: <ngrok_url>

components:
  securitySchemes:
    BotAuth:
      type: apiKey
      in: header
      name: x-bot-api-key
      
  schemas:
    # --- Enums ---
    MaintenanceCategoryEnum:
      type: string
      enum: [plumbing, electrical, hvac, carpentry, structural, cleaning, other]
    
    MaintenancePriorityEnum:
      type: string
      enum: [low, normal, high, urgent]
    
    VehicleTypeEnum:
      type: string
      enum: [two_wheeler, four_wheeler]
      description: "Use 'two_wheeler' for motorbikes/bikes, 'four_wheeler' for cars."

    # --- Response Schemas ---
    RichContext:
      type: object
      properties:
        meta:
          type: object
          properties:
            query_time: { type: string }
            tenant_name: { type: string }
        residency:
          type: object
          properties:
            active_contracts_count: { type: integer }
            spaces:
              type: array
              items:
                type: object
                properties:
                  room_number: { type: string }
                  building_name: { type: string }
                  status: { type: string }
        finance:
          type: object
          properties:
            unpaid_bills_count: { type: integer }
            history:
              type: array
              items:
                type: object
                properties:
                  id: { type: integer }
                  type: { type: string }
                  amount: { type: number }
                  status: { type: string }
                  due: { type: string }
        maintenance:
          type: object
          properties:
            history:
              type: array
              items:
                type: object
                properties:
                  id: { type: integer }
                  title: { type: string }
                  status: { type: string }
                  priority: { type: string }
                  created_at: { type: string }
        vehicles:
          type: object
          properties:
            pending_registrations:
              type: array
              items:
                type: object
                properties:
                  license_plate: { type: string }
                  status: { type: string }
            active_vehicles:
              type: array
              items:
                type: object
                properties:
                  plate: { type: string }
                  brand: { type: string }
                  parking_slot: { type: string }

security:
  - BotAuth: []

# --- API Endpoints ---
paths:

  # --- TOOL 1: CONTEXT (The Brain) ---
  /api/bot/context:
    get:
      summary: "Get Tenant Context"
      description: "CRITICAL: Call this tool FIRST. Retrieves identity, rooms, bills, maintenance history, and vehicle status."
      operationId: "getTenantContext"
      tags: [Context]
      parameters:
        - name: tenant_user_id
          in: query
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data: { $ref: '#/components/schemas/RichContext' }

  # --- TOOL 2: CREATE MAINTENANCE ---
  /api/bot/maintenance/create:
    post:
      summary: "Create Maintenance Request"
      operationId: "createMaintenanceRequest"
      tags: [Maintenance]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, title]
              properties:
                tenant_user_id: { type: integer }
                title: { type: string }
                description: { type: string }
                category: { $ref: '#/components/schemas/MaintenanceCategoryEnum' }
                priority: { $ref: '#/components/schemas/MaintenancePriorityEnum' }
      responses:
        '201': { description: "Created" }

  # --- TOOL 3: UPDATE MAINTENANCE ---
  /api/bot/maintenance/{id}:
    put:
      summary: "Update Maintenance Request"
      description: "Updates a pending request."
      operationId: "updateMaintenanceRequest"
      tags: [Maintenance]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
                title: { type: string }
                description: { type: string }
                priority: { $ref: '#/components/schemas/MaintenancePriorityEnum' }
      responses:
        '200': { description: "Updated" }
        
  # --- TOOL 4: DELETE MAINTENANCE ---
    delete:
      summary: "Delete Maintenance Request"
      operationId: "deleteMaintenanceRequest"
      tags: [Maintenance]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
      responses:
        '200': { description: "Deleted" }

  # --- TOOL 5: REGISTER VEHICLE ---
  /api/bot/vehicle-registration/create:
    post:
      summary: "Register Vehicle"
      description: "Create a new parking request. Ask for Plate, Brand, and Color."
      operationId: "createVehicleRegistration"
      tags: [Vehicle]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, type, license_plate]
              properties:
                tenant_user_id: { type: integer }
                type: { $ref: '#/components/schemas/VehicleTypeEnum' }
                license_plate: { type: string }
                brand: { type: string, description: "Vehicle Brand (e.g. Honda, Toyota)" }
                color: { type: string, description: "Vehicle Color" }
                start_date: { type: string, format: date, description: "YYYY-MM-DD" }
                end_date: { type: string, format: date, description: "Optional YYYY-MM-DD" }
                note: { type: string }
      responses:
        '201': { description: "Created" }

  # --- TOOL 6: UPDATE REGISTRATION ---
  /api/bot/vehicle-registration/{id}:
    put:
      summary: "Update Registration"
      operationId: "updateVehicleRegistration"
      tags: [Vehicle]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
                type: { $ref: '#/components/schemas/VehicleTypeEnum' }
                license_plate: { type: string }
                brand: { type: string }
                color: { type: string }
                start_date: { type: string, format: date }
                end_date: { type: string, format: date }
      responses:
        '200': { description: "Updated" }

  # --- TOOL 7: CANCEL REGISTRATION ---
  /api/bot/vehicle-registration/{id}/cancel:
    post:
      summary: "Cancel Registration"
      operationId: "cancelVehicleRegistration"
      tags: [Vehicle]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
                cancellation_reason: { type: string }
      responses:
        '200': { description: "Cancelled" }

  # --- TOOL 8: GET REGULATIONS ---
  /api/bot/regulations:
    get:
      summary: "Get Regulations"
      description: "Returns general and building-specific regulations for this tenant."
      operationId: "getRegulations"
      tags: [Regulations]
      parameters:
        - name: tenant_user_id
          in: query
          required: true
          schema: { type: integer }
      responses:
        '200': { description: "Success" }

  # --- TOOL 9: CREATE PAYMENT LINK ---
  /api/bot/create-payment:
    post:
      summary: "Create Payment Link"
      description: "Generates PayOS checkout URL."
      operationId: "createPaymentLink"
      tags: [Payment]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id, bill_id]
              properties:
                tenant_user_id: { type: integer }
                bill_id: 
                  type: array
                  items: 
                    type: integer
                  description: "Array of Bill IDs to pay. Example: [10] or [10, 15]."
      responses:
        '200': 
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      checkoutUrl: { type: string }

  # --- TOOL 10: DOWNLOAD CONTRACT ---
  /api/bot/contract/download:
    post:
      summary: "Get Contract File"
      description: "Generates S3 link. Handles multiple contracts via 'room_number' parameter."
      operationId: "getContractFile"
      tags: [Contract]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenant_user_id]
              properties:
                tenant_user_id: { type: integer }
                room_number: { type: string, description: "Optional: Specify room if tenant has multiple contracts" }
      responses:
        '200': 
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type: { type: string, enum: [single_link, multiple_choices] }
                      download_url: { type: string }
                      options: { type: array }
